### ISSUE TITLE
Validation issue with capacityCounter in Reservation Controller

### ISSUE THREAD

**Issue by dewtheoboe** [Luke4Parker/ReservationSystem#23]
The way the capacity counter currently works logic wise it will kick out a reservation for not enough tables if the combined party size of the new reservation and every reservation it overlaps with in any way is more than the capacity of the location. What this does not account for is if the new reservation overlaps with more than one reservation but those reservations don't overlap with each other and at any given time the capacity is not exceeded we should allow that new reservation to be made but they will be told not enough tables. I may have an idea for this but you should check my logic.

**Comment by dewtheoboe** [comment]
This is partially fixed? I'm not sure it scales that well for increasingly long reservations or numerous small reservations on top of each other but match MVP

**Comment by dewtheoboe** [comment]
Kayla did say what I put in is sufficient for MVP. I believe what I did won't work for every scenario of overlapping reservations that could exist but will likely pick up the most common ones. 

The only thing I could think of that would actually fully solve the issue would be to for loop through each 15 minute increment (assuming our front end would likely only let them make reservations in 15 minute increments) of the new reservation that is trying to be created and loop through each reservation existing for that location on that day to count the total capacity compared to location capacity and kick it out if any increment is too large. But that didn't seem like it would scale very well and was kind of resource inefficient. But technically more correct if we get extra time and want to try that later?

**Comment by Luke4Parker** [comment]
The issue was dual capacity counters when you only needed one. Commenting out the capacityCounter variable at the end of the first foreach loop fixed it.
